import { NormalizedProduct, CategoryInfo } from "./types";

// ─── Category Data ───

export const categories: CategoryInfo[] = [
  {
    slug: "smartphones",
    name: "Smartphones",
    icon: "📱",
    description: "Find the perfect phone for your needs",
    productCount: 245,
  },
  {
    slug: "laptops",
    name: "Laptops",
    icon: "💻",
    description: "Laptops for work, gaming, and everything in between",
    productCount: 189,
  },
  {
    slug: "earbuds",
    name: "Earbuds",
    icon: "🎧",
    description: "True wireless and wired earbuds compared",
    productCount: 156,
  },
  {
    slug: "televisions",
    name: "Televisions",
    icon: "📺",
    description: "Smart TVs from all major brands",
    productCount: 120,
  },
  {
    slug: "refrigerators",
    name: "Refrigerators",
    icon: "❄️",
    description: "Single door to side-by-side fridges",
    productCount: 98,
  },
  {
    slug: "washing-machines",
    name: "Washing Machines",
    icon: "🫧",
    description: "Top load, front load, and semi-automatic",
    productCount: 87,
  },
  {
    slug: "air-conditioners",
    name: "Air Conditioners",
    icon: "🌬️",
    description: "Split and window ACs for every room",
    productCount: 76,
  },
];

// ─── Mock Products ───

export const mockProducts: NormalizedProduct[] = [
  // ── Smartphones ──
  {
    id: "phone-1",
    canonicalName: "Samsung Galaxy S24 FE 5G",
    brand: "Samsung",
    category: "smartphones",
    listings: [
      {
        store: "amazon",
        price: 29999,
        originalPrice: 34999,
        rating: 4.3,
        reviewCount: 12450,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 30499,
        originalPrice: 34999,
        rating: 4.4,
        reviewCount: 8920,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "croma",
        price: 31999,
        originalPrice: 34999,
        rating: 4.2,
        reviewCount: 1250,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 29999,
    averageRating: 4.3,
    totalReviews: 22620,
    imageUrl: "/mock/phone-samsung.jpg",
    specifications: {
      Display: "6.7-inch Dynamic AMOLED 2X, 120Hz",
      Processor: "Exynos 2400e",
      RAM: "8 GB",
      Storage: "128 GB / 256 GB",
      Camera: "50MP + 12MP + 8MP | 10MP Front",
      Battery: "4700 mAh, 25W Fast Charging",
      OS: "Android 14, One UI 6.1",
    },
    highlights: [
      "Dynamic AMOLED 2X display with 120Hz refresh rate",
      "Triple camera setup with 50MP main sensor",
      "IP68 water and dust resistance",
      "7 years of OS and security updates",
    ],
    pros: [
      "Excellent display quality",
      "Great camera performance",
      "Long software support",
      "Good battery life",
    ],
    cons: [
      "Exynos processor instead of Snapdragon",
      "25W charging is slow for 2024",
      "No charger in the box",
    ],
    scores: { overall: 88, value: 85, performance: 86, reviews: 90, popularity: 92 },
  },
  {
    id: "phone-2",
    canonicalName: "OnePlus 12R 5G",
    brand: "OnePlus",
    category: "smartphones",
    listings: [
      {
        store: "amazon",
        price: 32999,
        originalPrice: 39999,
        rating: 4.5,
        reviewCount: 18200,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 33499,
        originalPrice: 39999,
        rating: 4.4,
        reviewCount: 15600,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 32999,
    averageRating: 4.45,
    totalReviews: 33800,
    imageUrl: "/mock/phone-oneplus.jpg",
    specifications: {
      Display: "6.78-inch LTPO AMOLED, 120Hz",
      Processor: "Snapdragon 8 Gen 2",
      RAM: "8 GB / 16 GB",
      Storage: "128 GB / 256 GB",
      Camera: "50MP + 8MP + 2MP | 16MP Front",
      Battery: "5500 mAh, 100W SUPERVOOC",
      OS: "Android 14, OxygenOS 14",
    },
    highlights: [
      "Snapdragon 8 Gen 2 for flagship performance",
      "100W fast charging, full in 26 minutes",
      "5500 mAh massive battery",
      "LTPO AMOLED display",
    ],
    pros: [
      "Blazing fast charging",
      "Excellent performance",
      "Huge battery",
      "Smooth 120Hz display",
    ],
    cons: [
      "Ultrawide camera is average",
      "No wireless charging",
      "Plastic frame",
    ],
    scores: { overall: 90, value: 92, performance: 91, reviews: 88, popularity: 95 },
  },
  {
    id: "phone-3",
    canonicalName: "iPhone 15",
    brand: "Apple",
    category: "smartphones",
    listings: [
      {
        store: "amazon",
        price: 57999,
        originalPrice: 69900,
        rating: 4.6,
        reviewCount: 25800,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 58499,
        originalPrice: 69900,
        rating: 4.5,
        reviewCount: 22100,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "croma",
        price: 61999,
        originalPrice: 69900,
        rating: 4.6,
        reviewCount: 5400,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 57999,
    averageRating: 4.57,
    totalReviews: 53300,
    imageUrl: "/mock/phone-iphone.jpg",
    specifications: {
      Display: "6.1-inch Super Retina XDR OLED",
      Processor: "A16 Bionic",
      RAM: "6 GB",
      Storage: "128 GB / 256 GB / 512 GB",
      Camera: "48MP + 12MP | 12MP Front",
      Battery: "3877 mAh, 20W Fast Charging",
      OS: "iOS 17",
    },
    highlights: [
      "Dynamic Island for alerts and activities",
      "48MP main camera with 2x telephoto",
      "USB-C port (finally!)",
      "Ceramic Shield front cover",
    ],
    pros: [
      "Best-in-class video recording",
      "Excellent ecosystem integration",
      "Premium build quality",
      "Long software support",
    ],
    cons: [
      "Expensive",
      "60Hz display in 2024",
      "Slow charging speed",
      "Limited customization",
    ],
    scores: { overall: 91, value: 72, performance: 89, reviews: 94, popularity: 98 },
  },

  // ── Laptops ──
  {
    id: "laptop-1",
    canonicalName: "ASUS Vivobook 15 (2024)",
    brand: "ASUS",
    category: "laptops",
    listings: [
      {
        store: "amazon",
        price: 45990,
        originalPrice: 58990,
        rating: 4.2,
        reviewCount: 8900,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 46490,
        originalPrice: 58990,
        rating: 4.3,
        reviewCount: 6200,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 45990,
    averageRating: 4.25,
    totalReviews: 15100,
    imageUrl: "/mock/laptop-asus.jpg",
    specifications: {
      Display: "15.6-inch FHD IPS, 144Hz",
      Processor: "AMD Ryzen 5 7530U",
      RAM: "16 GB DDR4",
      Storage: "512 GB NVMe SSD",
      Graphics: "AMD Radeon Integrated",
      Battery: "50Wh, ~7 hours",
      Weight: "1.7 kg",
    },
    highlights: [
      "144Hz display for smooth visuals",
      "16GB RAM for multitasking",
      "Backlit keyboard",
      "Thin and lightweight design",
    ],
    pros: [
      "Great value for money",
      "Good display for the price",
      "Decent performance for coding",
      "Lightweight and portable",
    ],
    cons: [
      "Average webcam quality",
      "Battery life could be better",
      "No dedicated GPU",
    ],
    scores: { overall: 84, value: 92, performance: 80, reviews: 85, popularity: 88 },
  },
  {
    id: "laptop-2",
    canonicalName: "Lenovo IdeaPad Slim 5",
    brand: "Lenovo",
    category: "laptops",
    listings: [
      {
        store: "amazon",
        price: 56990,
        originalPrice: 72999,
        rating: 4.4,
        reviewCount: 5600,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 57490,
        originalPrice: 72999,
        rating: 4.3,
        reviewCount: 4100,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "croma",
        price: 59999,
        originalPrice: 72999,
        rating: 4.4,
        reviewCount: 890,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 56990,
    averageRating: 4.37,
    totalReviews: 10590,
    imageUrl: "/mock/laptop-lenovo.jpg",
    specifications: {
      Display: '14-inch 2.8K OLED, 90Hz',
      Processor: "Intel Core i5-13500H",
      RAM: "16 GB DDR5",
      Storage: "512 GB NVMe SSD",
      Graphics: "Intel Iris Xe",
      Battery: "57Wh, ~10 hours",
      Weight: "1.46 kg",
    },
    highlights: [
      "Stunning 2.8K OLED display",
      "13th Gen Intel processor",
      "DDR5 RAM for future-proofing",
      "All-metal build quality",
    ],
    pros: [
      "Beautiful OLED display",
      "Excellent build quality",
      "Great keyboard and trackpad",
      "Strong battery life",
    ],
    cons: [
      "OLED may have burn-in over years",
      "No HDMI 2.1",
      "Slightly heavy for ultrabook",
    ],
    scores: { overall: 89, value: 86, performance: 87, reviews: 90, popularity: 85 },
  },
  {
    id: "laptop-3",
    canonicalName: "Apple MacBook Air M3",
    brand: "Apple",
    category: "laptops",
    listings: [
      {
        store: "amazon",
        price: 94900,
        originalPrice: 114900,
        rating: 4.7,
        reviewCount: 12500,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 95900,
        originalPrice: 114900,
        rating: 4.7,
        reviewCount: 9800,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "croma",
        price: 99900,
        originalPrice: 114900,
        rating: 4.8,
        reviewCount: 3200,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 94900,
    averageRating: 4.73,
    totalReviews: 25500,
    imageUrl: "/mock/laptop-macbook.jpg",
    specifications: {
      Display: "13.6-inch Liquid Retina, 500 nits",
      Processor: "Apple M3 (8-core CPU, 10-core GPU)",
      RAM: "8 GB Unified",
      Storage: "256 GB SSD",
      Graphics: "Integrated 10-core GPU",
      Battery: "52.6Wh, ~18 hours",
      Weight: "1.24 kg",
    },
    highlights: [
      "M3 chip for incredible performance",
      "18-hour battery life",
      "Fanless silent operation",
      "MagSafe charging",
    ],
    pros: [
      "Insane battery life",
      "Silent operation",
      "Premium build and display",
      "Best-in-class performance per watt",
    ],
    cons: [
      "Expensive",
      "Only 8GB base RAM",
      "Limited port selection",
      "macOS-only software ecosystem",
    ],
    scores: { overall: 93, value: 70, performance: 92, reviews: 96, popularity: 97 },
  },

  // ── Earbuds ──
  {
    id: "earbuds-1",
    canonicalName: "boAt Airdopes 141",
    brand: "boAt",
    category: "earbuds",
    listings: [
      {
        store: "amazon",
        price: 1099,
        originalPrice: 4490,
        rating: 3.9,
        reviewCount: 285000,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 1099,
        originalPrice: 4490,
        rating: 4.0,
        reviewCount: 195000,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 1099,
    averageRating: 3.95,
    totalReviews: 480000,
    imageUrl: "/mock/earbuds-boat.jpg",
    specifications: {
      Driver: "8mm Dynamic Drivers",
      ANC: "No",
      Battery: "42 hours total (case + buds)",
      Bluetooth: "5.1",
      WaterResistance: "IPX4",
      Weight: "4g per bud",
    },
    highlights: [
      "42 hours total battery life",
      "ENx noise cancellation for calls",
      "IPX4 water resistance",
      "Touch controls",
    ],
    pros: [
      "Incredible value for money",
      "Long battery life",
      "Comfortable fit",
      "Massive user base",
    ],
    cons: [
      "No ANC",
      "Average sound quality",
      "Plastic build",
      "No app support",
    ],
    scores: { overall: 76, value: 98, performance: 65, reviews: 78, popularity: 99 },
  },
  {
    id: "earbuds-2",
    canonicalName: "Samsung Galaxy Buds FE",
    brand: "Samsung",
    category: "earbuds",
    listings: [
      {
        store: "amazon",
        price: 4499,
        originalPrice: 6999,
        rating: 4.3,
        reviewCount: 18500,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 4699,
        originalPrice: 6999,
        rating: 4.2,
        reviewCount: 12300,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 4499,
    averageRating: 4.25,
    totalReviews: 30800,
    imageUrl: "/mock/earbuds-samsung.jpg",
    specifications: {
      Driver: "12mm Dynamic Driver",
      ANC: "Yes (Active Noise Cancellation)",
      Battery: "30 hours total",
      Bluetooth: "5.2",
      WaterResistance: "IPX2",
      Weight: "5.6g per bud",
    },
    highlights: [
      "Active Noise Cancellation",
      "12mm drivers for rich sound",
      "Samsung ecosystem integration",
      "360 Audio support",
    ],
    pros: [
      "Good ANC for the price",
      "Rich bass and clear mids",
      "Comfortable for long use",
      "Samsung ecosystem integration",
    ],
    cons: [
      "IPX2 only — not great for gym",
      "ANC not as strong as premium options",
      "Case is a fingerprint magnet",
    ],
    scores: { overall: 83, value: 88, performance: 82, reviews: 85, popularity: 80 },
  },
  {
    id: "earbuds-3",
    canonicalName: "Sony WF-1000XM5",
    brand: "Sony",
    category: "earbuds",
    listings: [
      {
        store: "amazon",
        price: 17990,
        originalPrice: 24990,
        rating: 4.5,
        reviewCount: 8900,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 18490,
        originalPrice: 24990,
        rating: 4.4,
        reviewCount: 5200,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "croma",
        price: 19990,
        originalPrice: 24990,
        rating: 4.6,
        reviewCount: 2100,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 17990,
    averageRating: 4.5,
    totalReviews: 16200,
    imageUrl: "/mock/earbuds-sony.jpg",
    specifications: {
      Driver: "8.4mm Dynamic Driver X",
      ANC: "Industry-leading ANC",
      Battery: "24 hours total",
      Bluetooth: "5.3 (LDAC, LC3)",
      WaterResistance: "IPX4",
      Weight: "5.9g per bud",
    },
    highlights: [
      "Industry-leading noise cancellation",
      "Hi-Res Audio with LDAC",
      "Speak-to-chat auto-pause",
      "Multipoint connection",
    ],
    pros: [
      "Best ANC in any earbuds",
      "Exceptional sound quality",
      "Compact and comfortable",
      "Excellent app with EQ",
    ],
    cons: [
      "Expensive",
      "Touch controls can misfire",
      "Foam tips degrade over time",
    ],
    scores: { overall: 94, value: 75, performance: 96, reviews: 92, popularity: 88 },
  },

  // ── Televisions ──
  {
    id: "tv-1",
    canonicalName: "Redmi Smart Fire TV 43-inch",
    brand: "Redmi",
    category: "televisions",
    listings: [
      {
        store: "amazon",
        price: 17999,
        originalPrice: 29999,
        rating: 4.1,
        reviewCount: 42000,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 17999,
        originalPrice: 29999,
        rating: 4.2,
        reviewCount: 38000,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 17999,
    averageRating: 4.15,
    totalReviews: 80000,
    imageUrl: "/mock/tv-redmi.jpg",
    specifications: {
      Display: '43-inch Full HD (1920x1080)',
      Panel: "IPS",
      SmartTV: "Fire TV built-in",
      Speakers: "24W Dual Speakers, Dolby Audio",
      HDMI: "3 ports",
      HDR: "HDR10",
    },
    highlights: [
      "Fire TV OS with Alexa built-in",
      "24W speakers with Dolby Audio",
      "HDR10 support",
      "3 HDMI ports",
    ],
    pros: [
      "Best budget smart TV",
      "Fire TV OS is smooth",
      "Good sound for the price",
      "Reliable Xiaomi service",
    ],
    cons: [
      "Full HD only, no 4K",
      "Average viewing angles",
      "Plastic build",
    ],
    scores: { overall: 80, value: 95, performance: 72, reviews: 82, popularity: 93 },
  },
  {
    id: "tv-2",
    canonicalName: "Samsung Crystal 4K Neo 55-inch",
    brand: "Samsung",
    category: "televisions",
    listings: [
      {
        store: "amazon",
        price: 39990,
        originalPrice: 64900,
        rating: 4.3,
        reviewCount: 15600,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 40490,
        originalPrice: 64900,
        rating: 4.2,
        reviewCount: 12300,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "croma",
        price: 42990,
        originalPrice: 64900,
        rating: 4.3,
        reviewCount: 4500,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 39990,
    averageRating: 4.27,
    totalReviews: 32400,
    imageUrl: "/mock/tv-samsung.jpg",
    specifications: {
      Display: '55-inch 4K UHD (3840x2160)',
      Panel: "VA",
      SmartTV: "Tizen OS",
      Speakers: "20W, Dolby Digital Plus",
      HDMI: "3 ports (1x eARC)",
      HDR: "HDR10+, HLG",
    },
    highlights: [
      "Crystal 4K processor",
      "HDR10+ for vivid colors",
      "Samsung Gaming Hub",
      "Slim and sleek design",
    ],
    pros: [
      "Excellent 4K picture quality",
      "Tizen OS is polished",
      "Good for gaming",
      "Samsung brand reliability",
    ],
    cons: [
      "Average speakers",
      "VA panel — narrow viewing angles",
      "No Dolby Vision",
    ],
    scores: { overall: 86, value: 84, performance: 85, reviews: 87, popularity: 90 },
  },

  // ── Refrigerators ──
  {
    id: "fridge-1",
    canonicalName: "Samsung 253L Frost Free Double Door",
    brand: "Samsung",
    category: "refrigerators",
    listings: [
      {
        store: "amazon",
        price: 24990,
        originalPrice: 31990,
        rating: 4.3,
        reviewCount: 9800,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 25490,
        originalPrice: 31990,
        rating: 4.2,
        reviewCount: 7200,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "croma",
        price: 26990,
        originalPrice: 31990,
        rating: 4.3,
        reviewCount: 2100,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 24990,
    averageRating: 4.27,
    totalReviews: 19100,
    imageUrl: "/mock/fridge-samsung.jpg",
    specifications: {
      Capacity: "253 Litres",
      Type: "Frost Free Double Door",
      EnergyRating: "3 Star",
      Compressor: "Digital Inverter",
      Warranty: "1 Year + 20 Years Compressor",
      Dimensions: "55.5 x 63.7 x 163.5 cm",
    },
    highlights: [
      "Digital Inverter compressor — energy efficient & quiet",
      "Convertible 5-in-1 modes",
      "All-around cooling",
      "20-year compressor warranty",
    ],
    pros: [
      "Excellent energy efficiency",
      "Quiet operation",
      "Convertible modes are useful",
      "20 year compressor warranty",
    ],
    cons: [
      "3-star rating, not 5-star",
      "Freezer capacity could be larger",
      "No water dispenser",
    ],
    scores: { overall: 85, value: 88, performance: 84, reviews: 86, popularity: 82 },
  },

  // ── Washing Machines ──
  {
    id: "wash-1",
    canonicalName: "LG 8 Kg Front Load Washing Machine",
    brand: "LG",
    category: "washing-machines",
    listings: [
      {
        store: "amazon",
        price: 33990,
        originalPrice: 44990,
        rating: 4.4,
        reviewCount: 6500,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 34490,
        originalPrice: 44990,
        rating: 4.3,
        reviewCount: 5100,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 33990,
    averageRating: 4.35,
    totalReviews: 11600,
    imageUrl: "/mock/wash-lg.jpg",
    specifications: {
      Capacity: "8 Kg",
      Type: "Front Load, Fully Automatic",
      Motor: "Direct Drive Inverter Motor",
      SpinSpeed: "1200 RPM",
      EnergyRating: "5 Star",
      Warranty: "2 Years + 10 Years Motor",
    },
    highlights: [
      "AI Direct Drive — detects fabric and optimizes wash",
      "Steam wash for allergen removal",
      "5-star energy rating",
      "10 year motor warranty",
    ],
    pros: [
      "AI-powered fabric detection",
      "Steam wash kills 99.9% allergens",
      "Very energy efficient",
      "Quiet direct drive motor",
    ],
    cons: [
      "Expensive upfront",
      "Longer wash cycles than top load",
      "Front load requires bending",
    ],
    scores: { overall: 88, value: 82, performance: 90, reviews: 88, popularity: 85 },
  },

  // ── Air Conditioners ──
  {
    id: "ac-1",
    canonicalName: "Daikin 1.5 Ton 5 Star Inverter Split AC",
    brand: "Daikin",
    category: "air-conditioners",
    listings: [
      {
        store: "amazon",
        price: 38990,
        originalPrice: 55200,
        rating: 4.3,
        reviewCount: 4200,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "flipkart",
        price: 39490,
        originalPrice: 55200,
        rating: 4.2,
        reviewCount: 3100,
        productUrl: "#",
        inStock: true,
      },
      {
        store: "croma",
        price: 41990,
        originalPrice: 55200,
        rating: 4.4,
        reviewCount: 1800,
        productUrl: "#",
        inStock: true,
      },
    ],
    bestPrice: 38990,
    averageRating: 4.3,
    totalReviews: 9100,
    imageUrl: "/mock/ac-daikin.jpg",
    specifications: {
      Capacity: "1.5 Ton",
      Type: "Split, Inverter",
      EnergyRating: "5 Star (2024)",
      Refrigerant: "R-32",
      CoolingCapacity: "5.28 kW",
      Noise: "32 dB (Indoor)",
    },
    highlights: [
      "5-star energy rating — lowest electricity bills",
      "R-32 eco-friendly refrigerant",
      "Coanda airflow for even cooling",
      "PM 2.5 filter",
    ],
    pros: [
      "Excellent energy efficiency",
      "Very quiet operation",
      "Daikin reliability and service",
      "Even cooling with Coanda",
    ],
    cons: [
      "Premium pricing",
      "No built-in Wi-Fi on base model",
      "Installation cost extra",
    ],
    scores: { overall: 89, value: 80, performance: 92, reviews: 88, popularity: 86 },
  },
];

// ─── Popular Search Suggestions ───

export const popularSearches = [
  "Best phone under ₹25,000 with great camera",
  "Best laptop under ₹60,000 for coding",
  "Best earbuds under ₹2,000",
  "Best 55-inch TV under ₹40,000",
  "Best refrigerator for family of 4",
  "Best washing machine under ₹35,000",
  "Best AC for bedroom under ₹40,000",
];
